server:
  port: 8081
  servlet:
    context-path: /aggregator

logging:
  level:
    root: DEBUG

--- # production
spring:
  profiles: prod
redis:
  uri: redis://O6L6ATk7Be@10.178.230.75:6379

--- # local
spring:
  profiles: local
  application:
    basePath: /swagger-ui.html
redis:
  uri: redis://localhost:6379/

