server:
  port: 8080
  servlet:
    context-path: /aggregator

logging:
  level:
    root: DEBUG

--- # production
spring:
  profiles: prod
redis:
  uri: redis://O6L6ATk7Be@10.178.230.75:6379
store:
  host: hotspot-store
  findByLocation: /store/api/v1/store/find/location/{x}/{y}
review:
  host: hotspot-evaluation
  findReviewByStoreId: /evaluation/review/store/{storeId}

--- # local
spring:
  profiles: local
  application:
    basePath: /swagger-ui.html
redis:
  uri: redis://localhost:6379/

store:
  host: localhost:8080
  findByLocation: /store/api/v1/store/find/location/{x}/{y}
review:
  host: localhost:8082
  findReviewByStoreId: /evaluation/review/store/{storeId}